/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2015
 *
 * Name: Dale Hartman, PJ Onusconich, and Adam Karl
 * Date: Nov 8, 2015
 * Time: 4:08:27 PM
 *
 * Project: csci205_finalproject
 * Package: view
 * File: MainView
 * Description:
 *
 * ****************************************
 */
package view;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author pjo006
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGameDialog = new javax.swing.JDialog();
        textP1Name = new javax.swing.JTextField();
        textP2Name = new javax.swing.JTextField();
        textP3Name = new javax.swing.JTextField();
        textP4Name = new javax.swing.JTextField();
        textP5Name = new javax.swing.JTextField();
        textP6Name = new javax.swing.JTextField();
        buttonConfirmStartGame = new javax.swing.JButton();
        buttonOpenNumPlayers = new javax.swing.JButton();
        lblMenuImage = new javax.swing.JLabel();
        numPlayersDialog = new javax.swing.JDialog();
        comboNumPlayers = new javax.swing.JComboBox();
        buttonConfirmNumPlayers = new javax.swing.JButton();
        comboNumAIPlayers = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        attackTransferDialog = new javax.swing.JDialog();
        lblAttackTransfer = new javax.swing.JLabel();
        buttonConfrimAttackTransfer = new javax.swing.JButton();
        comboNumArmies = new javax.swing.JComboBox();
        riskCardDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        lblRiskCard1 = new javax.swing.JLabel();
        lblRiskCard2 = new javax.swing.JLabel();
        lblRiskCard3 = new javax.swing.JLabel();
        lblRiskCard4 = new javax.swing.JLabel();
        lblRiskCard5 = new javax.swing.JLabel();
        buttonTradeIn = new javax.swing.JButton();
        buttonExitCards = new javax.swing.JButton();
        lblPlayer1Action = new javax.swing.JLabel();
        lblPlayer2Action = new javax.swing.JLabel();
        lblPlayer3Action = new javax.swing.JLabel();
        lblPlayer4Action = new javax.swing.JLabel();
        lblPlayer5Action = new javax.swing.JLabel();
        lblPlayer6Action = new javax.swing.JLabel();
        lblNEuropeArmies = new javax.swing.JLabel();
        lbNEuropeLogo = new javax.swing.JLabel();
        buttonNEurope = new javax.swing.JButton();
        lblUkraineArmies = new javax.swing.JLabel();
        lblUkraineLogo = new javax.swing.JLabel();
        buttonUkraine = new javax.swing.JButton();
        lblGreatBritainArmies = new javax.swing.JLabel();
        lblGreatBritainLogo = new javax.swing.JLabel();
        buttonGreatBritain = new javax.swing.JButton();
        lblIcelandArmies = new javax.swing.JLabel();
        lblIcelandLogo = new javax.swing.JLabel();
        buttonIceland = new javax.swing.JButton();
        lblMadagascarArmies = new javax.swing.JLabel();
        lblMadagascarLogo = new javax.swing.JLabel();
        buttonMadagascar = new javax.swing.JButton();
        lblEAfricaArmies = new javax.swing.JLabel();
        lblEAfricaLogo = new javax.swing.JLabel();
        buttonEAfrica = new javax.swing.JButton();
        lblEgyptArmies = new javax.swing.JLabel();
        lblEgyptLogo = new javax.swing.JLabel();
        buttonEgypt = new javax.swing.JButton();
        lblCongoArmies = new javax.swing.JLabel();
        lblCongoLogo = new javax.swing.JLabel();
        buttonCongo = new javax.swing.JButton();
        lblSAfricaArmies = new javax.swing.JLabel();
        lblSAfricaLogo = new javax.swing.JLabel();
        buttonSAfrica = new javax.swing.JButton();
        lblNAfricaArmies = new javax.swing.JLabel();
        lblNAfricaLogo = new javax.swing.JLabel();
        buttonNAfrica = new javax.swing.JButton();
        lblVenezuelaArmies = new javax.swing.JLabel();
        lblVenezuelaLogo = new javax.swing.JLabel();
        buttonVenezuela = new javax.swing.JButton();
        lblPeruArmies = new javax.swing.JLabel();
        lblPeruLogo = new javax.swing.JLabel();
        buttonPeru = new javax.swing.JButton();
        lblArgentinaArmies = new javax.swing.JLabel();
        lblArgentinaLogo = new javax.swing.JLabel();
        buttonArgentina = new javax.swing.JButton();
        lblBrazilArmies = new javax.swing.JLabel();
        lblBrazilLogo = new javax.swing.JLabel();
        buttonBrazil = new javax.swing.JButton();
        lblCentAmArmies = new javax.swing.JLabel();
        lblCentAmLogo = new javax.swing.JLabel();
        buttonCentAm = new javax.swing.JButton();
        lblQuebecArmies = new javax.swing.JLabel();
        lblQuebecLogo = new javax.swing.JLabel();
        buttonQuebec = new javax.swing.JButton();
        lblNWTerritoryArmies = new javax.swing.JLabel();
        lblNWTerritoryLogo = new javax.swing.JLabel();
        buttonNWTerritory = new javax.swing.JButton();
        lblGreenlandArmies = new javax.swing.JLabel();
        lblGreenlandLogo = new javax.swing.JLabel();
        buttonGreenland = new javax.swing.JButton();
        lblAlbertaArmies = new javax.swing.JLabel();
        lblAlbertaLogo = new javax.swing.JLabel();
        buttonAlberta = new javax.swing.JButton();
        lblAlaskaArmies = new javax.swing.JLabel();
        lblAlaskaLogo = new javax.swing.JLabel();
        buttonAlaska = new javax.swing.JButton();
        lblOntarioArmies = new javax.swing.JLabel();
        lblOntarioLogo = new javax.swing.JLabel();
        buttonOntario = new javax.swing.JButton();
        lblWEuropeArmies = new javax.swing.JLabel();
        lblWEuropeLogo = new javax.swing.JLabel();
        buttonWEurope = new javax.swing.JButton();
        lblSEuropeArmies = new javax.swing.JLabel();
        lblSEuropeLogo = new javax.swing.JLabel();
        buttonSEurope = new javax.swing.JButton();
        lblScandanaviaArmies = new javax.swing.JLabel();
        lblScandanaviaLogo = new javax.swing.JLabel();
        buttonScandanavia = new javax.swing.JButton();
        lblWUSArmies = new javax.swing.JLabel();
        lblWUSLogo = new javax.swing.JLabel();
        buttonWUS = new javax.swing.JButton();
        lblEUSArmies = new javax.swing.JLabel();
        lblEUSLogo = new javax.swing.JLabel();
        buttonEUS = new javax.swing.JButton();
        lblIndiaArmies = new javax.swing.JLabel();
        lblIndiaLogo = new javax.swing.JLabel();
        buttonIndia = new javax.swing.JButton();
        lblAfghanistanArmies = new javax.swing.JLabel();
        lblAfghanistanLogo = new javax.swing.JLabel();
        buttonAfghanistan = new javax.swing.JButton();
        lblChinaArmies = new javax.swing.JLabel();
        lblChinaLogo = new javax.swing.JLabel();
        buttonChina = new javax.swing.JButton();
        lblUralArmies = new javax.swing.JLabel();
        lblUralLogo = new javax.swing.JLabel();
        buttonUral = new javax.swing.JButton();
        lblSiamArmies = new javax.swing.JLabel();
        lblSiamLogo = new javax.swing.JLabel();
        buttonSiam = new javax.swing.JButton();
        lblSiberiaArmies = new javax.swing.JLabel();
        lblSiberiaLogo = new javax.swing.JLabel();
        buttonSiberia = new javax.swing.JButton();
        lblMongoliaArmies = new javax.swing.JLabel();
        lblMongoliaLogo = new javax.swing.JLabel();
        buttonMongolia = new javax.swing.JButton();
        lblIrkutskArmies = new javax.swing.JLabel();
        lblIrkutskLogo = new javax.swing.JLabel();
        buttonIrkutsk = new javax.swing.JButton();
        lblYakutskArmies = new javax.swing.JLabel();
        lblYakutskLogo = new javax.swing.JLabel();
        buttonYakutsk = new javax.swing.JButton();
        lblKamChatkaArmies = new javax.swing.JLabel();
        lblKamchatkaLogo = new javax.swing.JLabel();
        buttonKamchatka = new javax.swing.JButton();
        lblJapanArmies = new javax.swing.JLabel();
        lblJapanLogo = new javax.swing.JLabel();
        buttonJapan = new javax.swing.JButton();
        lblNewGuineaArmies = new javax.swing.JLabel();
        lblNewGuineaLogo = new javax.swing.JLabel();
        buttonNewGuinea = new javax.swing.JButton();
        lblIndonesiaArmies = new javax.swing.JLabel();
        lblIndonesiaLogo = new javax.swing.JLabel();
        buttonIndonesia = new javax.swing.JButton();
        lblEAustraliaArmies = new javax.swing.JLabel();
        lblEAustraliaLogo = new javax.swing.JLabel();
        buttonEAustralia = new javax.swing.JButton();
        lblWAustraliaArmies = new javax.swing.JLabel();
        lblWAustraliaLogo = new javax.swing.JLabel();
        buttonWAustralia = new javax.swing.JButton();
        lblMiddleEastArmies = new javax.swing.JLabel();
        lblMiddleEastLogo = new javax.swing.JLabel();
        buttonMiddleEast = new javax.swing.JButton();
        javax.swing.JLabel lblBoard = new javax.swing.JLabel();
        panelStartGame = new javax.swing.JPanel();
        buttonStartGame = new javax.swing.JButton();
        javax.swing.JLabel lblRiskImage = new javax.swing.JLabel();
        panelPlayers = new javax.swing.JPanel();
        lblPlayer1 = new javax.swing.JLabel();
        lblPlayer1Armies = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer2Armies = new javax.swing.JLabel();
        lblPlayer3 = new javax.swing.JLabel();
        lblPlayer3Armies = new javax.swing.JLabel();
        lblPlayer4 = new javax.swing.JLabel();
        lblPlayer4Armies = new javax.swing.JLabel();
        lblPlayer5 = new javax.swing.JLabel();
        lblPlayer5Armies = new javax.swing.JLabel();
        lblPlayer6 = new javax.swing.JLabel();
        lblPlayer6Armies = new javax.swing.JLabel();
        panelDice = new javax.swing.JPanel();
        lblAttackDie1 = new javax.swing.JLabel();
        lblDefendDie1 = new javax.swing.JLabel();
        lblAttackDie2 = new javax.swing.JLabel();
        lblDefendDie2 = new javax.swing.JLabel();
        lblAttackDie3 = new javax.swing.JLabel();
        javax.swing.JLabel lblPlayers = new javax.swing.JLabel();
        panelPlayerOptions = new javax.swing.JPanel();
        buttonRollDice = new javax.swing.JButton();
        buttonAttack = new javax.swing.JButton();
        buttonArmies = new javax.swing.JButton();
        buttonRiskCards = new javax.swing.JButton();
        buttonEndTurn = new javax.swing.JButton();

        startGameDialog.setAlwaysOnTop(true);
        startGameDialog.setLocation(new java.awt.Point(0, 0));
        startGameDialog.setMinimumSize(new java.awt.Dimension(570, 330));
        startGameDialog.setModal(true);
        startGameDialog.setSize(new java.awt.Dimension(560, 300));
        startGameDialog.getContentPane().setLayout(null);

        textP1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textP1NameActionPerformed(evt);
            }
        });
        startGameDialog.getContentPane().add(textP1Name);
        textP1Name.setBounds(10, 200, 70, 27);
        startGameDialog.getContentPane().add(textP2Name);
        textP2Name.setBounds(90, 200, 70, 27);
        startGameDialog.getContentPane().add(textP3Name);
        textP3Name.setBounds(170, 200, 70, 27);
        startGameDialog.getContentPane().add(textP4Name);
        textP4Name.setBounds(330, 200, 70, 27);
        startGameDialog.getContentPane().add(textP5Name);
        textP5Name.setBounds(410, 200, 70, 27);
        startGameDialog.getContentPane().add(textP6Name);
        textP6Name.setBounds(490, 200, 70, 27);

        buttonConfirmStartGame.setText("Start Game");
        buttonConfirmStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmStartGameActionPerformed(evt);
            }
        });
        startGameDialog.getContentPane().add(buttonConfirmStartGame);
        buttonConfirmStartGame.setBounds(320, 250, 180, 50);

        buttonOpenNumPlayers.setText("Set Number of Players");
        buttonOpenNumPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenNumPlayersActionPerformed(evt);
            }
        });
        startGameDialog.getContentPane().add(buttonOpenNumPlayers);
        buttonOpenNumPlayers.setBounds(70, 250, 180, 50);

        lblMenuImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/risklogo.jpg"))); // NOI18N
        startGameDialog.getContentPane().add(lblMenuImage);
        lblMenuImage.setBounds(0, 0, 570, 300);

        numPlayersDialog.setTitle("Select Number of Players");
        numPlayersDialog.setAlwaysOnTop(true);
        numPlayersDialog.setLocation(new java.awt.Point(0, 0));
        numPlayersDialog.setResizable(false);
        numPlayersDialog.setSize(new java.awt.Dimension(350, 150));
        numPlayersDialog.getContentPane().setLayout(null);

        comboNumPlayers.setMaximumRowCount(5);
        comboNumPlayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        comboNumPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumPlayersActionPerformed(evt);
            }
        });
        numPlayersDialog.getContentPane().add(comboNumPlayers);
        comboNumPlayers.setBounds(50, 50, 70, 25);

        buttonConfirmNumPlayers.setText("OK");
        numPlayersDialog.getContentPane().add(buttonConfirmNumPlayers);
        buttonConfirmNumPlayers.setBounds(150, 80, 44, 27);

        comboNumAIPlayers.setMaximumRowCount(7);
        comboNumAIPlayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        numPlayersDialog.getContentPane().add(comboNumAIPlayers);
        comboNumAIPlayers.setBounds(220, 50, 69, 25);

        jLabel1.setText("Number of Players:");
        numPlayersDialog.getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 118, 15);

        jLabel2.setText("Number of AI Players:");
        numPlayersDialog.getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 30, 133, 15);

        attackTransferDialog.setSize(new java.awt.Dimension(300, 150));
        attackTransferDialog.getContentPane().setLayout(null);

        lblAttackTransfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttackTransfer.setText("How many armies would you like to attack with?");
        lblAttackTransfer.setMaximumSize(new java.awt.Dimension(100, 15));
        lblAttackTransfer.setMinimumSize(new java.awt.Dimension(100, 15));
        lblAttackTransfer.setPreferredSize(new java.awt.Dimension(100, 15));
        attackTransferDialog.getContentPane().add(lblAttackTransfer);
        lblAttackTransfer.setBounds(0, 1, 300, 37);

        buttonConfrimAttackTransfer.setText("Attack!");
        buttonConfrimAttackTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfrimAttackTransferActionPerformed(evt);
            }
        });
        attackTransferDialog.getContentPane().add(buttonConfrimAttackTransfer);
        buttonConfrimAttackTransfer.setBounds(160, 70, 73, 27);

        comboNumArmies.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        comboNumArmies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumArmiesActionPerformed(evt);
            }
        });
        attackTransferDialog.getContentPane().add(comboNumArmies);
        comboNumArmies.setBounds(60, 70, 50, 25);

        riskCardDialog.setTitle("Risk Cards");
        riskCardDialog.setMinimumSize(new java.awt.Dimension(760, 300));
        riskCardDialog.setPreferredSize(new java.awt.Dimension(760, 300));
        riskCardDialog.setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new java.awt.GridLayout(1, 5));

        lblRiskCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/defaultCard.jpg"))); // NOI18N
        jPanel1.add(lblRiskCard1);

        lblRiskCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/defaultCard.jpg"))); // NOI18N
        jPanel1.add(lblRiskCard2);

        lblRiskCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/defaultCard.jpg"))); // NOI18N
        jPanel1.add(lblRiskCard3);

        lblRiskCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/defaultCard.jpg"))); // NOI18N
        jPanel1.add(lblRiskCard4);

        lblRiskCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/defaultCard.jpg"))); // NOI18N
        jPanel1.add(lblRiskCard5);

        buttonTradeIn.setText("Trade In");
        buttonTradeIn.setPreferredSize(new java.awt.Dimension(100, 40));

        buttonExitCards.setText("Exit");
        buttonExitCards.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout riskCardDialogLayout = new javax.swing.GroupLayout(riskCardDialog.getContentPane());
        riskCardDialog.getContentPane().setLayout(riskCardDialogLayout);
        riskCardDialogLayout.setHorizontalGroup(
            riskCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riskCardDialogLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(buttonExitCards, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(buttonTradeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(riskCardDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        riskCardDialogLayout.setVerticalGroup(
            riskCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riskCardDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(riskCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTradeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExitCards, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Risk");
        setBackground(new java.awt.Color(0, 0, 255));
        setPreferredSize(new java.awt.Dimension(1550, 950));
        setResizable(false);
        setSize(new java.awt.Dimension(1550, 950));
        getContentPane().setLayout(null);

        lblPlayer1Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/actionflag.png"))); // NOI18N
        lblPlayer1Action.setEnabled(false);
        getContentPane().add(lblPlayer1Action);
        lblPlayer1Action.setBounds(1300, 510, 30, 30);

        lblPlayer2Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/actionflagblue.png"))); // NOI18N
        lblPlayer2Action.setEnabled(false);
        getContentPane().add(lblPlayer2Action);
        lblPlayer2Action.setBounds(1300, 546, 30, 30);

        lblPlayer3Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/actionflaggreen.png"))); // NOI18N
        lblPlayer3Action.setEnabled(false);
        getContentPane().add(lblPlayer3Action);
        lblPlayer3Action.setBounds(1300, 582, 30, 30);

        lblPlayer4Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/actionflaggrey.png"))); // NOI18N
        lblPlayer4Action.setEnabled(false);
        getContentPane().add(lblPlayer4Action);
        lblPlayer4Action.setBounds(1300, 618, 30, 30);

        lblPlayer5Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/actionflagpink.png"))); // NOI18N
        lblPlayer5Action.setEnabled(false);
        getContentPane().add(lblPlayer5Action);
        lblPlayer5Action.setBounds(1300, 654, 30, 30);

        lblPlayer6Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/actionflagred.png"))); // NOI18N
        lblPlayer6Action.setEnabled(false);
        getContentPane().add(lblPlayer6Action);
        lblPlayer6Action.setBounds(1300, 690, 30, 30);

        lblNEuropeArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNEuropeArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNEuropeArmies.setText("0");
        getContentPane().add(lblNEuropeArmies);
        lblNEuropeArmies.setBounds(650, 270, 44, 15);

        lbNEuropeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lbNEuropeLogo);
        lbNEuropeLogo.setBounds(610, 120, 90, 190);

        buttonNEurope.setContentAreaFilled(false);
        buttonNEurope.setEnabled(false);
        buttonNEurope.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonNEurope);
        buttonNEurope.setBounds(600, 290, 90, 20);

        lblUkraineArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUkraineArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUkraineArmies.setText("0");
        getContentPane().add(lblUkraineArmies);
        lblUkraineArmies.setBounds(750, 260, 44, 15);

        lblUkraineLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblUkraineLogo);
        lblUkraineLogo.setBounds(710, 110, 90, 190);

        buttonUkraine.setContentAreaFilled(false);
        buttonUkraine.setEnabled(false);
        buttonUkraine.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonUkraine);
        buttonUkraine.setBounds(730, 220, 90, 20);

        lblGreatBritainArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblGreatBritainArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreatBritainArmies.setText("0");
        getContentPane().add(lblGreatBritainArmies);
        lblGreatBritainArmies.setBounds(520, 300, 44, 15);

        lblGreatBritainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblGreatBritainLogo);
        lblGreatBritainLogo.setBounds(480, 150, 90, 190);

        buttonGreatBritain.setContentAreaFilled(false);
        buttonGreatBritain.setEnabled(false);
        buttonGreatBritain.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonGreatBritain);
        buttonGreatBritain.setBounds(480, 270, 90, 20);

        lblIcelandArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblIcelandArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcelandArmies.setText("0");
        getContentPane().add(lblIcelandArmies);
        lblIcelandArmies.setBounds(560, 150, 44, 15);

        lblIcelandLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblIcelandLogo);
        lblIcelandLogo.setBounds(520, 0, 90, 190);

        buttonIceland.setContentAreaFilled(false);
        buttonIceland.setEnabled(false);
        buttonIceland.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonIceland);
        buttonIceland.setBounds(500, 180, 90, 20);

        lblMadagascarArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMadagascarArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMadagascarArmies.setText("0");
        getContentPane().add(lblMadagascarArmies);
        lblMadagascarArmies.setBounds(840, 720, 44, 15);

        lblMadagascarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblMadagascarLogo);
        lblMadagascarLogo.setBounds(800, 570, 90, 190);

        buttonMadagascar.setContentAreaFilled(false);
        buttonMadagascar.setEnabled(false);
        buttonMadagascar.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonMadagascar);
        buttonMadagascar.setBounds(770, 760, 90, 20);

        lblEAfricaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEAfricaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEAfricaArmies.setText("0");
        getContentPane().add(lblEAfricaArmies);
        lblEAfricaArmies.setBounds(740, 570, 44, 15);

        lblEAfricaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblEAfricaLogo);
        lblEAfricaLogo.setBounds(700, 420, 90, 190);

        buttonEAfrica.setContentAreaFilled(false);
        buttonEAfrica.setDefaultCapable(false);
        buttonEAfrica.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonEAfrica);
        buttonEAfrica.setBounds(720, 610, 90, 20);

        lblEgyptArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEgyptArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEgyptArmies.setText("0");
        getContentPane().add(lblEgyptArmies);
        lblEgyptArmies.setBounds(690, 480, 44, 15);

        lblEgyptLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblEgyptLogo);
        lblEgyptLogo.setBounds(650, 330, 90, 190);

        buttonEgypt.setContentAreaFilled(false);
        buttonEgypt.setEnabled(false);
        buttonEgypt.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonEgypt);
        buttonEgypt.setBounds(650, 510, 90, 20);

        lblCongoArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCongoArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCongoArmies.setText("0");
        getContentPane().add(lblCongoArmies);
        lblCongoArmies.setBounds(700, 640, 44, 15);

        lblCongoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblCongoLogo);
        lblCongoLogo.setBounds(660, 490, 90, 190);

        buttonCongo.setContentAreaFilled(false);
        buttonCongo.setDefaultCapable(false);
        buttonCongo.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonCongo);
        buttonCongo.setBounds(650, 660, 90, 20);

        lblSAfricaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSAfricaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSAfricaArmies.setText("0");
        getContentPane().add(lblSAfricaArmies);
        lblSAfricaArmies.setBounds(700, 800, 44, 15);

        lblSAfricaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblSAfricaLogo);
        lblSAfricaLogo.setBounds(660, 650, 90, 190);

        buttonSAfrica.setContentAreaFilled(false);
        buttonSAfrica.setEnabled(false);
        buttonSAfrica.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonSAfrica);
        buttonSAfrica.setBounds(660, 750, 90, 20);

        lblNAfricaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNAfricaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNAfricaArmies.setText("0");
        getContentPane().add(lblNAfricaArmies);
        lblNAfricaArmies.setBounds(590, 520, 44, 15);

        lblNAfricaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblNAfricaLogo);
        lblNAfricaLogo.setBounds(550, 370, 90, 190);

        buttonNAfrica.setContentAreaFilled(false);
        buttonNAfrica.setEnabled(false);
        buttonNAfrica.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonNAfrica);
        buttonNAfrica.setBounds(560, 550, 90, 20);

        lblVenezuelaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblVenezuelaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenezuelaArmies.setText("0");
        getContentPane().add(lblVenezuelaArmies);
        lblVenezuelaArmies.setBounds(330, 460, 44, 15);

        lblVenezuelaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblVenezuelaLogo);
        lblVenezuelaLogo.setBounds(290, 310, 90, 190);

        buttonVenezuela.setContentAreaFilled(false);
        buttonVenezuela.setEnabled(false);
        buttonVenezuela.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonVenezuela);
        buttonVenezuela.setBounds(260, 490, 90, 20);

        lblPeruArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPeruArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeruArmies.setText("0");
        getContentPane().add(lblPeruArmies);
        lblPeruArmies.setBounds(290, 590, 44, 15);

        lblPeruLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblPeruLogo);
        lblPeruLogo.setBounds(250, 440, 90, 190);

        buttonPeru.setContentAreaFilled(false);
        buttonPeru.setEnabled(false);
        buttonPeru.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonPeru);
        buttonPeru.setBounds(270, 610, 90, 20);

        lblArgentinaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblArgentinaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArgentinaArmies.setText("0");
        getContentPane().add(lblArgentinaArmies);
        lblArgentinaArmies.setBounds(330, 730, 44, 15);

        lblArgentinaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblArgentinaLogo);
        lblArgentinaLogo.setBounds(290, 580, 90, 190);

        buttonArgentina.setContentAreaFilled(false);
        buttonArgentina.setEnabled(false);
        buttonArgentina.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonArgentina);
        buttonArgentina.setBounds(300, 690, 90, 20);

        lblBrazilArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBrazilArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrazilArmies.setText("0");
        getContentPane().add(lblBrazilArmies);
        lblBrazilArmies.setBounds(410, 610, 44, 15);

        lblBrazilLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblBrazilLogo);
        lblBrazilLogo.setBounds(370, 460, 90, 190);

        buttonBrazil.setContentAreaFilled(false);
        buttonBrazil.setEnabled(false);
        buttonBrazil.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonBrazil);
        buttonBrazil.setBounds(350, 570, 90, 20);

        lblCentAmArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCentAmArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCentAmArmies.setText("0");
        getContentPane().add(lblCentAmArmies);
        lblCentAmArmies.setBounds(170, 440, 44, 15);

        lblCentAmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblCentAmLogo);
        lblCentAmLogo.setBounds(130, 290, 90, 190);

        buttonCentAm.setContentAreaFilled(false);
        buttonCentAm.setEnabled(false);
        buttonCentAm.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonCentAm);
        buttonCentAm.setBounds(170, 410, 90, 20);

        lblQuebecArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQuebecArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuebecArmies.setText("0");
        getContentPane().add(lblQuebecArmies);
        lblQuebecArmies.setBounds(390, 250, 44, 15);

        lblQuebecLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblQuebecLogo);
        lblQuebecLogo.setBounds(350, 100, 60, 190);

        buttonQuebec.setContentAreaFilled(false);
        buttonQuebec.setEnabled(false);
        buttonQuebec.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonQuebec);
        buttonQuebec.setBounds(330, 220, 90, 20);

        lblNWTerritoryArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNWTerritoryArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNWTerritoryArmies.setText("0");
        getContentPane().add(lblNWTerritoryArmies);
        lblNWTerritoryArmies.setBounds(220, 90, 44, 15);

        lblNWTerritoryLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblNWTerritoryLogo);
        lblNWTerritoryLogo.setBounds(180, -60, 90, 190);

        buttonNWTerritory.setContentAreaFilled(false);
        buttonNWTerritory.setEnabled(false);
        buttonNWTerritory.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonNWTerritory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNWTerritoryActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNWTerritory);
        buttonNWTerritory.setBounds(160, 140, 90, 20);

        lblGreenlandArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblGreenlandArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreenlandArmies.setText("0");
        getContentPane().add(lblGreenlandArmies);
        lblGreenlandArmies.setBounds(450, 110, 44, 15);

        lblGreenlandLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblGreenlandLogo);
        lblGreenlandLogo.setBounds(410, -40, 90, 190);

        buttonGreenland.setContentAreaFilled(false);
        buttonGreenland.setEnabled(false);
        buttonGreenland.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonGreenland);
        buttonGreenland.setBounds(400, 80, 90, 20);

        lblAlbertaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAlbertaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlbertaArmies.setText("0");
        getContentPane().add(lblAlbertaArmies);
        lblAlbertaArmies.setBounds(200, 240, 44, 15);

        lblAlbertaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblAlbertaLogo);
        lblAlbertaLogo.setBounds(160, 90, 60, 190);

        buttonAlberta.setContentAreaFilled(false);
        buttonAlberta.setEnabled(false);
        buttonAlberta.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonAlberta);
        buttonAlberta.setBounds(150, 200, 90, 20);

        lblAlaskaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAlaskaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlaskaArmies.setText("0");
        getContentPane().add(lblAlaskaArmies);
        lblAlaskaArmies.setBounds(90, 120, 44, 15);

        lblAlaskaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblAlaskaLogo);
        lblAlaskaLogo.setBounds(50, -20, 60, 160);

        buttonAlaska.setContentAreaFilled(false);
        buttonAlaska.setEnabled(false);
        buttonAlaska.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonAlaska);
        buttonAlaska.setBounds(40, 140, 90, 20);

        lblOntarioArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblOntarioArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOntarioArmies.setText("0");
        getContentPane().add(lblOntarioArmies);
        lblOntarioArmies.setBounds(290, 200, 44, 15);

        lblOntarioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblOntarioLogo);
        lblOntarioLogo.setBounds(250, 50, 90, 190);

        buttonOntario.setContentAreaFilled(false);
        buttonOntario.setEnabled(false);
        buttonOntario.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonOntario);
        buttonOntario.setBounds(240, 230, 90, 20);

        lblWEuropeArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblWEuropeArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWEuropeArmies.setText("0");
        getContentPane().add(lblWEuropeArmies);
        lblWEuropeArmies.setBounds(500, 400, 44, 15);

        lblWEuropeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblWEuropeLogo);
        lblWEuropeLogo.setBounds(460, 250, 90, 190);

        buttonWEurope.setContentAreaFilled(false);
        buttonWEurope.setEnabled(false);
        buttonWEurope.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonWEurope);
        buttonWEurope.setBounds(520, 380, 90, 20);

        lblSEuropeArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSEuropeArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSEuropeArmies.setText("0");
        getContentPane().add(lblSEuropeArmies);
        lblSEuropeArmies.setBounds(650, 400, 44, 15);

        lblSEuropeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblSEuropeLogo);
        lblSEuropeLogo.setBounds(610, 250, 90, 190);

        buttonSEurope.setContentAreaFilled(false);
        buttonSEurope.setEnabled(false);
        buttonSEurope.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonSEurope);
        buttonSEurope.setBounds(610, 360, 90, 20);

        lblScandanaviaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblScandanaviaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScandanaviaArmies.setText("0");
        getContentPane().add(lblScandanaviaArmies);
        lblScandanaviaArmies.setBounds(670, 130, 44, 15);

        lblScandanaviaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblScandanaviaLogo);
        lblScandanaviaLogo.setBounds(630, -10, 90, 190);

        buttonScandanavia.setContentAreaFilled(false);
        buttonScandanavia.setEnabled(false);
        buttonScandanavia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonScandanavia);
        buttonScandanavia.setBounds(620, 170, 90, 20);

        lblWUSArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblWUSArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWUSArmies.setText("0");
        getContentPane().add(lblWUSArmies);
        lblWUSArmies.setBounds(200, 330, 44, 15);

        lblWUSLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblWUSLogo);
        lblWUSLogo.setBounds(160, 180, 90, 190);

        buttonWUS.setContentAreaFilled(false);
        buttonWUS.setEnabled(false);
        buttonWUS.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonWUS);
        buttonWUS.setBounds(160, 290, 90, 20);

        lblEUSArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEUSArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEUSArmies.setText("0");
        getContentPane().add(lblEUSArmies);
        lblEUSArmies.setBounds(320, 300, 44, 15);

        lblEUSLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblEUSLogo);
        lblEUSLogo.setBounds(280, 150, 90, 190);

        buttonEUS.setContentAreaFilled(false);
        buttonEUS.setEnabled(false);
        buttonEUS.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonEUS);
        buttonEUS.setBounds(240, 330, 90, 20);

        lblIndiaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblIndiaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndiaArmies.setText("0");
        getContentPane().add(lblIndiaArmies);
        lblIndiaArmies.setBounds(930, 430, 44, 15);

        lblIndiaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblIndiaLogo);
        lblIndiaLogo.setBounds(890, 280, 90, 190);

        buttonIndia.setContentAreaFilled(false);
        buttonIndia.setEnabled(false);
        buttonIndia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonIndia);
        buttonIndia.setBounds(890, 450, 90, 20);

        lblAfghanistanArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAfghanistanArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAfghanistanArmies.setText("0");
        getContentPane().add(lblAfghanistanArmies);
        lblAfghanistanArmies.setBounds(870, 350, 44, 15);

        lblAfghanistanLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblAfghanistanLogo);
        lblAfghanistanLogo.setBounds(830, 200, 90, 190);

        buttonAfghanistan.setContentAreaFilled(false);
        buttonAfghanistan.setEnabled(false);
        buttonAfghanistan.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonAfghanistan);
        buttonAfghanistan.setBounds(830, 310, 90, 20);

        lblChinaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblChinaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChinaArmies.setText("0");
        getContentPane().add(lblChinaArmies);
        lblChinaArmies.setBounds(1030, 420, 44, 15);

        lblChinaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblChinaLogo);
        lblChinaLogo.setBounds(990, 270, 90, 190);

        buttonChina.setContentAreaFilled(false);
        buttonChina.setEnabled(false);
        buttonChina.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonChina);
        buttonChina.setBounds(980, 380, 90, 20);

        lblUralArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUralArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUralArmies.setText("0");
        getContentPane().add(lblUralArmies);
        lblUralArmies.setBounds(900, 250, 44, 15);

        lblUralLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblUralLogo);
        lblUralLogo.setBounds(860, 100, 90, 190);

        buttonUral.setContentAreaFilled(false);
        buttonUral.setEnabled(false);
        buttonUral.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonUral);
        buttonUral.setBounds(850, 210, 90, 20);

        lblSiamArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSiamArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSiamArmies.setText("0");
        getContentPane().add(lblSiamArmies);
        lblSiamArmies.setBounds(1030, 480, 44, 15);

        lblSiamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblSiamLogo);
        lblSiamLogo.setBounds(990, 330, 90, 190);

        buttonSiam.setContentAreaFilled(false);
        buttonSiam.setEnabled(false);
        buttonSiam.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonSiam);
        buttonSiam.setBounds(1010, 500, 90, 20);

        lblSiberiaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSiberiaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSiberiaArmies.setText("0");
        getContentPane().add(lblSiberiaArmies);
        lblSiberiaArmies.setBounds(960, 170, 44, 15);

        lblSiberiaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblSiberiaLogo);
        lblSiberiaLogo.setBounds(920, 20, 90, 190);

        buttonSiberia.setContentAreaFilled(false);
        buttonSiberia.setEnabled(false);
        buttonSiberia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonSiberia);
        buttonSiberia.setBounds(910, 140, 90, 20);

        lblMongoliaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMongoliaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMongoliaArmies.setText("0");
        getContentPane().add(lblMongoliaArmies);
        lblMongoliaArmies.setBounds(1050, 330, 44, 15);

        lblMongoliaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblMongoliaLogo);
        lblMongoliaLogo.setBounds(1010, 180, 90, 190);

        buttonMongolia.setContentAreaFilled(false);
        buttonMongolia.setEnabled(false);
        buttonMongolia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonMongolia);
        buttonMongolia.setBounds(1010, 300, 90, 20);

        lblIrkutskArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblIrkutskArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIrkutskArmies.setText("0");
        getContentPane().add(lblIrkutskArmies);
        lblIrkutskArmies.setBounds(1020, 250, 44, 15);

        lblIrkutskLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblIrkutskLogo);
        lblIrkutskLogo.setBounds(980, 100, 90, 190);

        buttonIrkutsk.setContentAreaFilled(false);
        buttonIrkutsk.setEnabled(false);
        buttonIrkutsk.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonIrkutsk);
        buttonIrkutsk.setBounds(1000, 220, 90, 20);

        lblYakutskArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblYakutskArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYakutskArmies.setText("0");
        getContentPane().add(lblYakutskArmies);
        lblYakutskArmies.setBounds(1050, 130, 44, 15);

        lblYakutskLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblYakutskLogo);
        lblYakutskLogo.setBounds(1010, -20, 90, 190);

        buttonYakutsk.setContentAreaFilled(false);
        buttonYakutsk.setEnabled(false);
        buttonYakutsk.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonYakutsk);
        buttonYakutsk.setBounds(1020, 100, 90, 20);

        lblKamChatkaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblKamChatkaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKamChatkaArmies.setText("0");
        getContentPane().add(lblKamChatkaArmies);
        lblKamChatkaArmies.setBounds(1160, 130, 44, 22);

        lblKamchatkaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblKamchatkaLogo);
        lblKamchatkaLogo.setBounds(1120, 0, 90, 160);

        buttonKamchatka.setContentAreaFilled(false);
        buttonKamchatka.setEnabled(false);
        buttonKamchatka.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonKamchatka);
        buttonKamchatka.setBounds(1120, 100, 90, 20);

        lblJapanArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJapanArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJapanArmies.setText("0");
        getContentPane().add(lblJapanArmies);
        lblJapanArmies.setBounds(1200, 290, 44, 15);

        lblJapanLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblJapanLogo);
        lblJapanLogo.setBounds(1160, 140, 90, 190);

        buttonJapan.setContentAreaFilled(false);
        buttonJapan.setEnabled(false);
        buttonJapan.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonJapan);
        buttonJapan.setBounds(1140, 310, 90, 20);

        lblNewGuineaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNewGuineaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewGuineaArmies.setText("0");
        getContentPane().add(lblNewGuineaArmies);
        lblNewGuineaArmies.setBounds(1170, 570, 44, 15);

        lblNewGuineaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblNewGuineaLogo);
        lblNewGuineaLogo.setBounds(1130, 420, 90, 190);

        buttonNewGuinea.setContentAreaFilled(false);
        buttonNewGuinea.setEnabled(false);
        buttonNewGuinea.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonNewGuinea);
        buttonNewGuinea.setBounds(1130, 600, 90, 20);

        lblIndonesiaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblIndonesiaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndonesiaArmies.setText("0");
        getContentPane().add(lblIndonesiaArmies);
        lblIndonesiaArmies.setBounds(1050, 610, 44, 15);

        lblIndonesiaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblIndonesiaLogo);
        lblIndonesiaLogo.setBounds(1010, 460, 90, 190);

        buttonIndonesia.setContentAreaFilled(false);
        buttonIndonesia.setEnabled(false);
        buttonIndonesia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonIndonesia);
        buttonIndonesia.setBounds(1020, 630, 90, 20);

        lblEAustraliaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEAustraliaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEAustraliaArmies.setText("0");
        getContentPane().add(lblEAustraliaArmies);
        lblEAustraliaArmies.setBounds(1230, 770, 44, 15);

        lblEAustraliaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblEAustraliaLogo);
        lblEAustraliaLogo.setBounds(1190, 620, 90, 190);

        buttonEAustralia.setContentAreaFilled(false);
        buttonEAustralia.setEnabled(false);
        buttonEAustralia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonEAustralia);
        buttonEAustralia.setBounds(1150, 720, 90, 20);

        lblWAustraliaArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblWAustraliaArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWAustraliaArmies.setText("0");
        getContentPane().add(lblWAustraliaArmies);
        lblWAustraliaArmies.setBounds(1110, 730, 44, 15);

        lblWAustraliaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblWAustraliaLogo);
        lblWAustraliaLogo.setBounds(1070, 580, 90, 190);

        buttonWAustralia.setContentAreaFilled(false);
        buttonWAustralia.setEnabled(false);
        buttonWAustralia.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonWAustralia);
        buttonWAustralia.setBounds(1070, 760, 90, 20);

        lblMiddleEastArmies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMiddleEastArmies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiddleEastArmies.setText("0");
        getContentPane().add(lblMiddleEastArmies);
        lblMiddleEastArmies.setBounds(780, 460, 44, 15);

        lblMiddleEastLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/armylogo.png"))); // NOI18N
        getContentPane().add(lblMiddleEastLogo);
        lblMiddleEastLogo.setBounds(740, 310, 90, 190);

        buttonMiddleEast.setContentAreaFilled(false);
        buttonMiddleEast.setEnabled(false);
        buttonMiddleEast.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(buttonMiddleEast);
        buttonMiddleEast.setBounds(750, 420, 90, 20);

        lblBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/riskboard.jpg"))); // NOI18N
        lblBoard.setOpaque(true);
        getContentPane().add(lblBoard);
        lblBoard.setBounds(0, 0, 1302, 907);

        buttonStartGame.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonStartGame.setText("Start Game");

        lblRiskImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/risklogo.png"))); // NOI18N

        javax.swing.GroupLayout panelStartGameLayout = new javax.swing.GroupLayout(panelStartGame);
        panelStartGame.setLayout(panelStartGameLayout);
        panelStartGameLayout.setHorizontalGroup(
            panelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRiskImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(buttonStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        panelStartGameLayout.setVerticalGroup(
            panelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStartGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRiskImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelStartGame);
        panelStartGame.setBounds(1308, 729, 226, 178);

        panelPlayers.setLayout(new java.awt.GridLayout(0, 2));

        lblPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer1.setText("Player1");
        panelPlayers.add(lblPlayer1);

        lblPlayer1Armies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer1Armies.setText("Armies: 0");
        panelPlayers.add(lblPlayer1Armies);

        lblPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer2.setText("Player2");
        panelPlayers.add(lblPlayer2);

        lblPlayer2Armies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer2Armies.setText("Armies: 0");
        panelPlayers.add(lblPlayer2Armies);

        lblPlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer3.setText("Player3");
        panelPlayers.add(lblPlayer3);

        lblPlayer3Armies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer3Armies.setText("Armies: 0");
        panelPlayers.add(lblPlayer3Armies);

        lblPlayer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer4.setText("Player4");
        panelPlayers.add(lblPlayer4);

        lblPlayer4Armies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer4Armies.setText("Armies: 0");
        panelPlayers.add(lblPlayer4Armies);

        lblPlayer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer5.setText("Player5");
        panelPlayers.add(lblPlayer5);

        lblPlayer5Armies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer5Armies.setText("Armies: 0");
        panelPlayers.add(lblPlayer5Armies);

        lblPlayer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer6.setText("Player6");
        panelPlayers.add(lblPlayer6);

        lblPlayer6Armies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer6Armies.setText("Armies: 0");
        panelPlayers.add(lblPlayer6Armies);

        getContentPane().add(panelPlayers);
        panelPlayers.setBounds(1308, 503, 220, 220);

        panelDice.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        panelDice.setLayout(new java.awt.GridLayout(0, 2, 3, 3));

        lblAttackDie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dicewhiteblank.png"))); // NOI18N
        lblAttackDie1.setToolTipText("");
        panelDice.add(lblAttackDie1);

        lblDefendDie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dicewhiteblank.png"))); // NOI18N
        panelDice.add(lblDefendDie1);

        lblAttackDie2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dicewhiteblank.png"))); // NOI18N
        panelDice.add(lblAttackDie2);

        lblDefendDie2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dicewhiteblank.png"))); // NOI18N
        panelDice.add(lblDefendDie2);

        lblAttackDie3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dicewhiteblank.png"))); // NOI18N
        panelDice.add(lblAttackDie3);

        getContentPane().add(panelDice);
        panelDice.setBounds(1310, 10, 230, 220);

        lblPlayers.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblPlayers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayers.setText("Player List:");
        getContentPane().add(lblPlayers);
        lblPlayers.setBounds(1370, 470, 100, 31);

        panelPlayerOptions.setLayout(new java.awt.GridLayout(0, 1));

        buttonRollDice.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonRollDice.setText("Roll Dice");
        buttonRollDice.setEnabled(false);
        panelPlayerOptions.add(buttonRollDice);

        buttonAttack.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonAttack.setText("Attack");
        buttonAttack.setEnabled(false);
        buttonAttack.setMaximumSize(new java.awt.Dimension(100, 38));
        panelPlayerOptions.add(buttonAttack);

        buttonArmies.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonArmies.setText("Move/Add Armies");
        buttonArmies.setEnabled(false);
        buttonArmies.setPreferredSize(new java.awt.Dimension(103, 38));
        panelPlayerOptions.add(buttonArmies);

        buttonRiskCards.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonRiskCards.setText("Risk Cards");
        buttonRiskCards.setEnabled(false);
        buttonRiskCards.setMaximumSize(new java.awt.Dimension(100, 38));
        panelPlayerOptions.add(buttonRiskCards);

        buttonEndTurn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonEndTurn.setText("End Turn");
        buttonEndTurn.setEnabled(false);
        buttonEndTurn.setMaximumSize(new java.awt.Dimension(100, 38));
        panelPlayerOptions.add(buttonEndTurn);

        getContentPane().add(panelPlayerOptions);
        panelPlayerOptions.setBounds(1310, 230, 230, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDialog getAttackTransferDialog() {
        return attackTransferDialog;
    }

    public JButton getButtonConfrimAttackTransfer() {
        return buttonConfrimAttackTransfer;
    }

    public JComboBox getComboNumArmies() {
        return comboNumArmies;
    }

    public JLabel getLblAttackTransfer() {
        return lblAttackTransfer;
    }

    private void buttonConfirmStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmStartGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfirmStartGameActionPerformed

    private void buttonOpenNumPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenNumPlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOpenNumPlayersActionPerformed

    private void comboNumPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumPlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumPlayersActionPerformed

    private void textP1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textP1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textP1NameActionPerformed

    private void buttonNWTerritoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNWTerritoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNWTerritoryActionPerformed

    private void buttonConfrimAttackTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfrimAttackTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfrimAttackTransferActionPerformed

    private void comboNumArmiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumArmiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumArmiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    public JButton getButtonStartGame() {
        return buttonStartGame;
    }

    public JDialog getStartGameDialog() {
        return startGameDialog;
    }

    public JButton getButtonAfghanistan() {
        return buttonAfghanistan;
    }

    public JButton getButtonAlaska() {
        return buttonAlaska;
    }

    public JButton getButtonAlberta() {
        return buttonAlberta;
    }

    public JButton getButtonArgentina() {
        return buttonArgentina;
    }

    public JButton getButtonArmies() {
        return buttonArmies;
    }

    public JButton getButtonAttack() {
        return buttonAttack;
    }

    public JButton getButtonBrazil() {
        return buttonBrazil;
    }

    public JButton getButtonCentAm() {
        return buttonCentAm;
    }

    public JButton getButtonChina() {
        return buttonChina;
    }

    public JButton getButtonCongo() {
        return buttonCongo;
    }

    public JButton getButtonEAfrica() {
        return buttonEAfrica;
    }

    public JButton getButtonEAustralia() {
        return buttonEAustralia;
    }

    public JButton getButtonEUS() {
        return buttonEUS;
    }

    public JButton getButtonEgypt() {
        return buttonEgypt;
    }

    public JButton getButtonEndTurn() {
        return buttonEndTurn;
    }

    public JButton getButtonGreatBritain() {
        return buttonGreatBritain;
    }

    public JButton getButtonGreenland() {
        return buttonGreenland;
    }

    public JButton getButtonIceland() {
        return buttonIceland;
    }

    public JButton getButtonIndia() {
        return buttonIndia;
    }

    public JButton getButtonIndonesia() {
        return buttonIndonesia;
    }

    public JButton getButtonIrkutsk() {
        return buttonIrkutsk;
    }

    public JButton getButtonJapan() {
        return buttonJapan;
    }

    public JButton getButtonKamchatka() {
        return buttonKamchatka;
    }

    public JButton getButtonMadagascar() {
        return buttonMadagascar;
    }

    public JButton getButtonMiddleEast() {
        return buttonMiddleEast;
    }

    public JButton getButtonMongolia() {
        return buttonMongolia;
    }

    public JButton getButtonNAfrica() {
        return buttonNAfrica;
    }

    public JButton getButtonNEurope() {
        return buttonNEurope;
    }

    public JButton getButtonNWTerritory() {
        return buttonNWTerritory;
    }

    public JButton getButtonNewGuinea() {
        return buttonNewGuinea;
    }

    public JButton getButtonOntario() {
        return buttonOntario;
    }

    public JButton getButtonPeru() {
        return buttonPeru;
    }

    public JButton getButtonQuebec() {
        return buttonQuebec;
    }

    public JButton getButtonRiskCards() {
        return buttonRiskCards;
    }

    public JButton getButtonRollDice() {
        return buttonRollDice;
    }

    public JLabel getLblAttackDie1() {
        return lblAttackDie1;
    }

    public JLabel getLblAttackDie2() {
        return lblAttackDie2;
    }

    public JLabel getLblAttackDie3() {
        return lblAttackDie3;
    }

    public JLabel getLblDefendDie1() {
        return lblDefendDie1;
    }

    public JLabel getLblDefendDie2() {
        return lblDefendDie2;
    }

    public JButton getButtonSAfrica() {
        return buttonSAfrica;
    }

    public JButton getButtonSEurope() {
        return buttonSEurope;
    }

    public JButton getButtonScandanavia() {
        return buttonScandanavia;
    }

    public JButton getButtonSiam() {
        return buttonSiam;
    }

    public JButton getButtonSiberia() {
        return buttonSiberia;
    }

    public JButton getButtonUkraine() {
        return buttonUkraine;
    }

    public JButton getButtonUral() {
        return buttonUral;
    }

    public JButton getButtonVenezuela() {
        return buttonVenezuela;
    }

    public JButton getButtonWAustralia() {
        return buttonWAustralia;
    }

    public JButton getButtonWEurope() {
        return buttonWEurope;
    }

    public JButton getButtonWUS() {
        return buttonWUS;
    }

    public JButton getButtonYakutsk() {
        return buttonYakutsk;
    }

    public JLabel getLbCongoArmies() {
        return lblCongoArmies;
    }

    public JLabel getLbNEuropeLogo() {
        return lbNEuropeLogo;
    }

    public JLabel getLblAfghanistanArmies() {
        return lblAfghanistanArmies;
    }

    public JLabel getLblAfghanistanLogo() {
        return lblAfghanistanLogo;
    }

    public JLabel getLblAlaskaArmies() {
        return lblAlaskaArmies;
    }

    public JLabel getLblAlaskaLogo() {
        return lblAlaskaLogo;
    }

    public JLabel getLblAlbertaArmies() {
        return lblAlbertaArmies;
    }

    public JLabel getLblAlbertaLogo() {
        return lblAlbertaLogo;
    }

    public JLabel getLblArgentinaArmies() {
        return lblArgentinaArmies;
    }

    public JLabel getLblArgentinaLogo() {
        return lblArgentinaLogo;
    }

    public JLabel getLblBrazilArmies() {
        return lblBrazilArmies;
    }

    public JLabel getLblBrazilLogo() {
        return lblBrazilLogo;
    }

    public JLabel getLblCentAmArmies() {
        return lblCentAmArmies;
    }

    public JLabel getLblCentAmLogo() {
        return lblCentAmLogo;
    }

    public JLabel getLblChinaArmies() {
        return lblChinaArmies;
    }

    public JLabel getLblChinaLogo() {
        return lblChinaLogo;
    }

    public JLabel getLblCongoLogo() {
        return lblCongoLogo;
    }

    public JLabel getLblEAfricaArmies() {
        return lblEAfricaArmies;
    }

    public JLabel getLblEAfricaLogo() {
        return lblEAfricaLogo;
    }

    public JLabel getLblEAustraliaArmies() {
        return lblEAustraliaArmies;
    }

    public JLabel getLblEAustraliaLogo() {
        return lblEAustraliaLogo;
    }

    public JLabel getLblEUSArmies() {
        return lblEUSArmies;
    }

    public JLabel getLblEUSLogo() {
        return lblEUSLogo;
    }

    public JLabel getLblEgyptArmies() {
        return lblEgyptArmies;
    }

    public JLabel getLblEgyptLogo() {
        return lblEgyptLogo;
    }

    public JLabel getLblGreatBritainArmies() {
        return lblGreatBritainArmies;
    }

    public JLabel getLblGreatBritainLogo() {
        return lblGreatBritainLogo;
    }

    public JLabel getLblGreenlandArmies() {
        return lblGreenlandArmies;
    }

    public JLabel getLblGreenlandLogo() {
        return lblGreenlandLogo;
    }

    public JLabel getLblIcelandArmies() {
        return lblIcelandArmies;
    }

    public JLabel getLblIcelandLogo() {
        return lblIcelandLogo;
    }

    public JLabel getLblIndiaArmies() {
        return lblIndiaArmies;
    }

    public JLabel getLblIndiaLogo() {
        return lblIndiaLogo;
    }

    public JLabel getLblIndonesiaArmies() {
        return lblIndonesiaArmies;
    }

    public JLabel getLblIndonesiaLogo() {
        return lblIndonesiaLogo;
    }

    public JLabel getLblIrkutskArmies() {
        return lblIrkutskArmies;
    }

    public JLabel getLblIrkutskLogo() {
        return lblIrkutskLogo;
    }

    public JLabel getLblJapanArmies() {
        return lblJapanArmies;
    }

    public JLabel getLblJapanLogo() {
        return lblJapanLogo;
    }

    public JLabel getLblKamChatkaArmies() {
        return lblKamChatkaArmies;
    }

    public JLabel getLblKamchatkaLogo() {
        return lblKamchatkaLogo;
    }

    public JLabel getLblMadagascarArmies() {
        return lblMadagascarArmies;
    }

    public JLabel getLblMadagascarLogo() {
        return lblMadagascarLogo;
    }

    public JLabel getLblMenuImage() {
        return lblMenuImage;
    }

    public JLabel getLblMiddleEastArmies() {
        return lblMiddleEastArmies;
    }

    public JLabel getLblMiddleEastLogo() {
        return lblMiddleEastLogo;
    }

    public JLabel getLblMongoliaArmies() {
        return lblMongoliaArmies;
    }

    public JLabel getLblMongoliaLogo() {
        return lblMongoliaLogo;
    }

    public JLabel getLblNAfricaArmies() {
        return lblNAfricaArmies;
    }

    public JLabel getLblNAfricaLogo() {
        return lblNAfricaLogo;
    }

    public JLabel getLblNEuropeArmies() {
        return lblNEuropeArmies;
    }

    public JLabel getLblNWTerritoryArmies() {
        return lblNWTerritoryArmies;
    }

    public JLabel getLblNWTerritoryLogo() {
        return lblNWTerritoryLogo;
    }

    public JLabel getLblNewGuineaArmies() {
        return lblNewGuineaArmies;
    }

    public JLabel getLblNewGuineaLogo() {
        return lblNewGuineaLogo;
    }

    public JLabel getLblOntarioArmies() {
        return lblOntarioArmies;
    }

    public JLabel getLblOntarioLogo() {
        return lblOntarioLogo;
    }

    public JLabel getLblPeruArmies() {
        return lblPeruArmies;
    }

    public JLabel getLblPeruLogo() {
        return lblPeruLogo;
    }

    public JLabel getLblQuebecArmies() {
        return lblQuebecArmies;
    }

    public JLabel getLblQuebecLogo() {
        return lblQuebecLogo;
    }

    public JLabel getLblSAfricaArmies() {
        return lblSAfricaArmies;
    }

    public JLabel getLblSAfricaLogo() {
        return lblSAfricaLogo;
    }

    public JLabel getLblSEuropeArmies() {
        return lblSEuropeArmies;
    }

    public JLabel getLblSEuropeLogo() {
        return lblSEuropeLogo;
    }

    public JLabel getLblScandanaviaArmies() {
        return lblScandanaviaArmies;
    }

    public JLabel getLblScandanaviaLogo() {
        return lblScandanaviaLogo;
    }

    public JLabel getLblSiamArmies() {
        return lblSiamArmies;
    }

    public JLabel getLblSiamLogo() {
        return lblSiamLogo;
    }

    public JLabel getLblSiberiaArmies() {
        return lblSiberiaArmies;
    }

    public JLabel getLblSiberiaLogo() {
        return lblSiberiaLogo;
    }

    public JLabel getLblUkraineArmies() {
        return lblUkraineArmies;
    }

    public JLabel getLblUkraineLogo() {
        return lblUkraineLogo;
    }

    public JLabel getLblUralArmies() {
        return lblUralArmies;
    }

    public JLabel getLblUralLogo() {
        return lblUralLogo;
    }

    public JLabel getLblVenezuelaArmies() {
        return lblVenezuelaArmies;
    }

    public JLabel getLblVenezuelaLogo() {
        return lblVenezuelaLogo;
    }

    public JLabel getLblWAustraliaArmies() {
        return lblWAustraliaArmies;
    }

    public JLabel getLblWAustraliaLogo() {
        return lblWAustraliaLogo;
    }

    public JLabel getLblWEuropeArmies() {
        return lblWEuropeArmies;
    }

    public JLabel getLblWEuropeLogo() {
        return lblWEuropeLogo;
    }

    public JLabel getLblWUSArmies() {
        return lblWUSArmies;
    }

    public JLabel getLblWUSLogo() {
        return lblWUSLogo;
    }

    public JLabel getLblYakutskArmies() {
        return lblYakutskArmies;
    }

    public JLabel getLblYakutskLogo() {
        return lblYakutskLogo;
    }

    public JButton getButtonOpenNumPlayers() {
        return buttonOpenNumPlayers;
    }

    public JDialog getNumPlayersDialog() {
        return numPlayersDialog;
    }

    public JButton getButtonConfirmNumPlayers() {
        return buttonConfirmNumPlayers;
    }

    public JComboBox getComboNumPlayers() {
        return comboNumPlayers;
    }

    public JComboBox getComboNumAIPlayers() {
        return comboNumAIPlayers;
    }

    public JTextField getTextP1Name() {
        return textP1Name;
    }

    public JTextField getTextP2Name() {
        return textP2Name;
    }

    public JTextField getTextP3Name() {
        return textP3Name;
    }

    public JTextField getTextP4Name() {
        return textP4Name;
    }

    public JTextField getTextP5Name() {
        return textP5Name;
    }

    public JTextField getTextP6Name() {
        return textP6Name;
    }

    public JButton getButtonConfirmStartGame() {
        return buttonConfirmStartGame;
    }

    public JLabel getLblPlayer1() {
        return lblPlayer1;
    }

    public JLabel getLblPlayer2() {
        return lblPlayer2;
    }

    public JLabel getLblPlayer3() {
        return lblPlayer3;
    }

    public JLabel getLblPlayer4() {
        return lblPlayer4;
    }

    public JLabel getLblPlayer5() {
        return lblPlayer5;
    }

    public JLabel getLblPlayer6() {
        return lblPlayer6;
    }

    public JLabel getLblPlayer1Action() {
        return lblPlayer1Action;
    }

    public JLabel getLblPlayer2Action() {
        return lblPlayer2Action;
    }

    public JLabel getLblPlayer3Action() {
        return lblPlayer3Action;
    }

    public JLabel getLblPlayer4Action() {
        return lblPlayer4Action;
    }

    public JLabel getLblPlayer5Action() {
        return lblPlayer5Action;
    }

    public JLabel getLblPlayer6Action() {
        return lblPlayer6Action;
    }

    public JLabel getLblPlayer1Armies() {
        return lblPlayer1Armies;
    }

    public JLabel getLblPlayer2Armies() {
        return lblPlayer2Armies;
    }

    public JLabel getLblPlayer3Armies() {
        return lblPlayer3Armies;
    }

    public JLabel getLblPlayer4Armies() {
        return lblPlayer4Armies;
    }

    public JLabel getLblPlayer5Armies() {
        return lblPlayer5Armies;
    }

    public JLabel getLblPlayer6Armies() {
        return lblPlayer6Armies;
    }

    public JButton getButtonExitCards() {
        return buttonExitCards;
    }

    public JButton getButtonTradeIn() {
        return buttonTradeIn;
    }

    public JLabel getLblRiskCard1() {
        return lblRiskCard1;
    }

    public JLabel getLblRiskCard2() {
        return lblRiskCard2;
    }

    public JLabel getLblRiskCard3() {
        return lblRiskCard3;
    }

    public JLabel getLblRiskCard4() {
        return lblRiskCard4;
    }

    public JLabel getLblRiskCard5() {
        return lblRiskCard5;
    }

    public JDialog getRiskCardDialog() {
        return riskCardDialog;
    }

    /**
     * Returns a list of all the labels where the number of armies are printed
     *
     * @return
     */
    public ArrayList<JLabel> getLblPlayerArmies() {
        ArrayList armyLabels = new ArrayList<JLabel>();
        armyLabels.add(lblPlayer1Armies);
        armyLabels.add(lblPlayer2Armies);
        armyLabels.add(lblPlayer3Armies);
        armyLabels.add(lblPlayer4Armies);
        armyLabels.add(lblPlayer5Armies);
        armyLabels.add(lblPlayer6Armies);
        return armyLabels;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog attackTransferDialog;
    private javax.swing.JButton buttonAfghanistan;
    private javax.swing.JButton buttonAlaska;
    private javax.swing.JButton buttonAlberta;
    private javax.swing.JButton buttonArgentina;
    private javax.swing.JButton buttonArmies;
    private javax.swing.JButton buttonAttack;
    private javax.swing.JButton buttonBrazil;
    private javax.swing.JButton buttonCentAm;
    private javax.swing.JButton buttonChina;
    private javax.swing.JButton buttonConfirmNumPlayers;
    private javax.swing.JButton buttonConfirmStartGame;
    private javax.swing.JButton buttonConfrimAttackTransfer;
    private javax.swing.JButton buttonCongo;
    private javax.swing.JButton buttonEAfrica;
    private javax.swing.JButton buttonEAustralia;
    private javax.swing.JButton buttonEUS;
    private javax.swing.JButton buttonEgypt;
    private javax.swing.JButton buttonEndTurn;
    private javax.swing.JButton buttonExitCards;
    private javax.swing.JButton buttonGreatBritain;
    private javax.swing.JButton buttonGreenland;
    private javax.swing.JButton buttonIceland;
    private javax.swing.JButton buttonIndia;
    private javax.swing.JButton buttonIndonesia;
    private javax.swing.JButton buttonIrkutsk;
    private javax.swing.JButton buttonJapan;
    private javax.swing.JButton buttonKamchatka;
    private javax.swing.JButton buttonMadagascar;
    private javax.swing.JButton buttonMiddleEast;
    private javax.swing.JButton buttonMongolia;
    private javax.swing.JButton buttonNAfrica;
    private javax.swing.JButton buttonNEurope;
    private javax.swing.JButton buttonNWTerritory;
    private javax.swing.JButton buttonNewGuinea;
    private javax.swing.JButton buttonOntario;
    private javax.swing.JButton buttonOpenNumPlayers;
    private javax.swing.JButton buttonPeru;
    private javax.swing.JButton buttonQuebec;
    private javax.swing.JButton buttonRiskCards;
    private javax.swing.JButton buttonRollDice;
    private javax.swing.JButton buttonSAfrica;
    private javax.swing.JButton buttonSEurope;
    private javax.swing.JButton buttonScandanavia;
    private javax.swing.JButton buttonSiam;
    private javax.swing.JButton buttonSiberia;
    private javax.swing.JButton buttonStartGame;
    private javax.swing.JButton buttonTradeIn;
    private javax.swing.JButton buttonUkraine;
    private javax.swing.JButton buttonUral;
    private javax.swing.JButton buttonVenezuela;
    private javax.swing.JButton buttonWAustralia;
    private javax.swing.JButton buttonWEurope;
    private javax.swing.JButton buttonWUS;
    private javax.swing.JButton buttonYakutsk;
    private javax.swing.JComboBox comboNumAIPlayers;
    private javax.swing.JComboBox comboNumArmies;
    private javax.swing.JComboBox comboNumPlayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNEuropeLogo;
    private javax.swing.JLabel lblAfghanistanArmies;
    private javax.swing.JLabel lblAfghanistanLogo;
    private javax.swing.JLabel lblAlaskaArmies;
    private javax.swing.JLabel lblAlaskaLogo;
    private javax.swing.JLabel lblAlbertaArmies;
    private javax.swing.JLabel lblAlbertaLogo;
    private javax.swing.JLabel lblArgentinaArmies;
    private javax.swing.JLabel lblArgentinaLogo;
    private javax.swing.JLabel lblAttackDie1;
    private javax.swing.JLabel lblAttackDie2;
    private javax.swing.JLabel lblAttackDie3;
    private javax.swing.JLabel lblAttackTransfer;
    private javax.swing.JLabel lblBrazilArmies;
    private javax.swing.JLabel lblBrazilLogo;
    private javax.swing.JLabel lblCentAmArmies;
    private javax.swing.JLabel lblCentAmLogo;
    private javax.swing.JLabel lblChinaArmies;
    private javax.swing.JLabel lblChinaLogo;
    private javax.swing.JLabel lblCongoArmies;
    private javax.swing.JLabel lblCongoLogo;
    private javax.swing.JLabel lblDefendDie1;
    private javax.swing.JLabel lblDefendDie2;
    private javax.swing.JLabel lblEAfricaArmies;
    private javax.swing.JLabel lblEAfricaLogo;
    private javax.swing.JLabel lblEAustraliaArmies;
    private javax.swing.JLabel lblEAustraliaLogo;
    private javax.swing.JLabel lblEUSArmies;
    private javax.swing.JLabel lblEUSLogo;
    private javax.swing.JLabel lblEgyptArmies;
    private javax.swing.JLabel lblEgyptLogo;
    private javax.swing.JLabel lblGreatBritainArmies;
    private javax.swing.JLabel lblGreatBritainLogo;
    private javax.swing.JLabel lblGreenlandArmies;
    private javax.swing.JLabel lblGreenlandLogo;
    private javax.swing.JLabel lblIcelandArmies;
    private javax.swing.JLabel lblIcelandLogo;
    private javax.swing.JLabel lblIndiaArmies;
    private javax.swing.JLabel lblIndiaLogo;
    private javax.swing.JLabel lblIndonesiaArmies;
    private javax.swing.JLabel lblIndonesiaLogo;
    private javax.swing.JLabel lblIrkutskArmies;
    private javax.swing.JLabel lblIrkutskLogo;
    private javax.swing.JLabel lblJapanArmies;
    private javax.swing.JLabel lblJapanLogo;
    private javax.swing.JLabel lblKamChatkaArmies;
    private javax.swing.JLabel lblKamchatkaLogo;
    private javax.swing.JLabel lblMadagascarArmies;
    private javax.swing.JLabel lblMadagascarLogo;
    private javax.swing.JLabel lblMenuImage;
    private javax.swing.JLabel lblMiddleEastArmies;
    private javax.swing.JLabel lblMiddleEastLogo;
    private javax.swing.JLabel lblMongoliaArmies;
    private javax.swing.JLabel lblMongoliaLogo;
    private javax.swing.JLabel lblNAfricaArmies;
    private javax.swing.JLabel lblNAfricaLogo;
    private javax.swing.JLabel lblNEuropeArmies;
    private javax.swing.JLabel lblNWTerritoryArmies;
    private javax.swing.JLabel lblNWTerritoryLogo;
    private javax.swing.JLabel lblNewGuineaArmies;
    private javax.swing.JLabel lblNewGuineaLogo;
    private javax.swing.JLabel lblOntarioArmies;
    private javax.swing.JLabel lblOntarioLogo;
    private javax.swing.JLabel lblPeruArmies;
    private javax.swing.JLabel lblPeruLogo;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer1Action;
    private javax.swing.JLabel lblPlayer1Armies;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer2Action;
    private javax.swing.JLabel lblPlayer2Armies;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblPlayer3Action;
    private javax.swing.JLabel lblPlayer3Armies;
    private javax.swing.JLabel lblPlayer4;
    private javax.swing.JLabel lblPlayer4Action;
    private javax.swing.JLabel lblPlayer4Armies;
    private javax.swing.JLabel lblPlayer5;
    private javax.swing.JLabel lblPlayer5Action;
    private javax.swing.JLabel lblPlayer5Armies;
    private javax.swing.JLabel lblPlayer6;
    private javax.swing.JLabel lblPlayer6Action;
    private javax.swing.JLabel lblPlayer6Armies;
    private javax.swing.JLabel lblQuebecArmies;
    private javax.swing.JLabel lblQuebecLogo;
    private javax.swing.JLabel lblRiskCard1;
    private javax.swing.JLabel lblRiskCard2;
    private javax.swing.JLabel lblRiskCard3;
    private javax.swing.JLabel lblRiskCard4;
    private javax.swing.JLabel lblRiskCard5;
    private javax.swing.JLabel lblSAfricaArmies;
    private javax.swing.JLabel lblSAfricaLogo;
    private javax.swing.JLabel lblSEuropeArmies;
    private javax.swing.JLabel lblSEuropeLogo;
    private javax.swing.JLabel lblScandanaviaArmies;
    private javax.swing.JLabel lblScandanaviaLogo;
    private javax.swing.JLabel lblSiamArmies;
    private javax.swing.JLabel lblSiamLogo;
    private javax.swing.JLabel lblSiberiaArmies;
    private javax.swing.JLabel lblSiberiaLogo;
    private javax.swing.JLabel lblUkraineArmies;
    private javax.swing.JLabel lblUkraineLogo;
    private javax.swing.JLabel lblUralArmies;
    private javax.swing.JLabel lblUralLogo;
    private javax.swing.JLabel lblVenezuelaArmies;
    private javax.swing.JLabel lblVenezuelaLogo;
    private javax.swing.JLabel lblWAustraliaArmies;
    private javax.swing.JLabel lblWAustraliaLogo;
    private javax.swing.JLabel lblWEuropeArmies;
    private javax.swing.JLabel lblWEuropeLogo;
    private javax.swing.JLabel lblWUSArmies;
    private javax.swing.JLabel lblWUSLogo;
    private javax.swing.JLabel lblYakutskArmies;
    private javax.swing.JLabel lblYakutskLogo;
    private javax.swing.JDialog numPlayersDialog;
    private javax.swing.JPanel panelDice;
    private javax.swing.JPanel panelPlayerOptions;
    private javax.swing.JPanel panelPlayers;
    private javax.swing.JPanel panelStartGame;
    private javax.swing.JDialog riskCardDialog;
    private javax.swing.JDialog startGameDialog;
    private javax.swing.JTextField textP1Name;
    private javax.swing.JTextField textP2Name;
    private javax.swing.JTextField textP3Name;
    private javax.swing.JTextField textP4Name;
    private javax.swing.JTextField textP5Name;
    private javax.swing.JTextField textP6Name;
    // End of variables declaration//GEN-END:variables
}
